### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by skyfox1977** [nickn17/enirodashboard#1]
It would be nice to have the version number somewhere, maybe on the middle button,  like top right or bottom right, or maybe even separate menu that also contains release notes, or both.

**Comment by nickn17** [comment]
Done. Added version to menu .. and under  BLE not connected message. It will work from next version.  Release notes is in readme.txt.

**Comment by stvjfp1** [comment]
Just innstalled Evdash, but the version number says 1.8.3b? Should it not be 2.2.0?
