### ISSUE TITLE
Is it possible to add Kona EV in vehicule list

### ISSUE THREAD

**Issue by stgauvin** [nickn17/enirodashboard#2]
Is it possible to add Kona EV in vehicule list.

**Comment by romanmatyus** [comment]
@nickn17  Or Citigo iV? If it's technically possible, I can help with it.

**Comment by nickn17** [comment]
@stgauvin Kona EV is already added. Sorry, I didn't notice issue this notice. 
@romanmatyus  Yes, it will be great. But you have to found OBD2 commands, ECUs/registers and locate values. For Niro/Kona it's was easy thanks to this project https://github.com/JejuSoul/OBD-PIDs-for-HKMC-EVs
Is it something similiar for Citigoe? Can you contact me via nick.n17@gmail.com
We can continue via hangouts, whatapp, telegram, or emails.

**Comment by romanmatyus** [comment]
@nickn17 I found something in https://readthedocs.org/projects/ovms/downloads/pdf/latest/

**Comment by nickn17** [comment]
@romanmatyus  Can you analyze it ? And prepare data for programming ? I have this document for eniro https://docs.google.com/spreadsheets/d/1HAtaFV3EbaJiPP7Do0RaK1vz7oIfOJlEVY7AUmXq5gI/edit?usp=sharing
We can do something similiar for citigo. 

Enirodashboard is doing this via obd .. It contacts units (7e2, 7e4,.. ) in the loop and request and parse data from registers (22C101, 22C102, 2101, etc). Citigo has different units with different registers.

-> init phase
  "AT Z",      // Reset all
  "AT I",      // Print the version ID
  "AT S0",     // Printing of spaces on
  "AT E0",     // Echo off
  "AT L0",     // Linefeeds off
  "AT SP 6",   // Select protocol to ISO 15765-4 CAN (11 bit ID, 500 kbit/s)
  "AT DP",
  "AT ST16",    // reduced timeout to 1, orig.16

->>> Loop phase 

  // ABS / ESP + AHB
  "ATSH7D1",
  "22C101",     // brake, park/drive mode

  // IGPM
  "ATSH770",
  "22BC03",     // low beam
  "22BC06",     // brake light

  // VMCU
  "ATSH7E2",
  "2101",     // speed, ...
  "2102",     // aux, ...

  // BMS
  "ATSH7E4",
  "220101",   // power kw, ...
  "220102",   // cell voltages
  "220103",   // cell voltages
  "220104",   // cell voltages
  "220105",   // soh, soc, ..
  "220106",   // cooling water temp

  // Aircondition
  "ATSH7B3",
  "220100",   // in/out temp
  "220102",   // coolant temp1, 2

  // BCM / TPMS
  "ATSH7A0",
  "22c00b",   // tire pressure/temp

  // CLUSTER MODULE
  "ATSH7C6",
  "22B002",   // odo

**Comment by romanmatyus** [comment]
I'll try it
